Disable building tests on Windows.
TestPlugin.dll can't be built under Windows for the next LLVM update,
due to issues with unsatisfied library dependencies. We don't run these
tests on Windows, so disabling them would also reduce build times.

Test: ./build.py works

FAILED: : && /c/android_trees/llvm-toolchain/prebuilts/gcc/linux-x86/host/x86_64-w64-mingw32-4.8/bin/x86_64-w64-mingw32-g++  --sysroot=/c/android_trees/llvm-toolchain/prebuilts/gcc/linux-x86/host/x86_64-w64-mingw32-4.8/x86_64-w64-mingw32  -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wa,-mbig-obj -std=gnu++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment  -O2 -DNDEBUG  -Wl,--allow-multiple-definition -shared -o unittests/Passes/TestPlugin.dll -Wl,--major-image-version,0,--minor-image-version,0 unittests/Passes/CMakeFiles/TestPlugin.dir/TestPlugin.cpp.obj  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && :
unittests/Passes/CMakeFiles/TestPlugin.dir/TestPlugin.cpp.obj:TestPlugin.cpp:(.text$_ZN4llvm6detail9PassModelINS_6ModuleE14TestModulePassNS_17PreservedAnalysesENS_15AnalysisManagerIS2_IEEEIEE3runERS2_RS6_[_ZN4llvm6detail9PassModelINS_6ModuleE14TestModulePassNS_17PreservedAnalysesENS_15AnalysisManagerIS2_IEEEIEE3runERS2_RS6_]+0x47): undefined reference to `llvm::PreservedAnalyses::AllAnalysesKey'
unittests/Passes/CMakeFiles/TestPlugin.dir/TestPlugin.cpp.obj:TestPlugin.cpp:(.text$_ZN4llvm6detail9PassModelINS_6ModuleE14TestModulePassNS_17PreservedAnalysesENS_15AnalysisManagerIS2_IEEEIEE4nameEv[_ZN4llvm6detail9PassModelINS_6ModuleE14TestModulePassNS_17PreservedAnalysesENS_15AnalysisManagerIS2_IEEEIEE4nameEv]+0x42): undefined reference to `llvm::StringRef::find(llvm::StringRef, unsigned long long) const'
unittests/Passes/CMakeFiles/TestPlugin.dir/TestPlugin.cpp.obj:TestPlugin.cpp:(.text$_ZN4llvm23SmallVectorTemplateBaseISt8functionIFbNS_9StringRefERNS_11PassManagerINS_6ModuleENS_15AnalysisManagerIS4_IEEEIEEENS_8ArrayRefINS_11PassBuilder15PipelineElementEEEEELb0EE4growEy[_ZN4llvm23SmallVectorTemplateBaseISt8functionIFbNS_9StringRefERNS_11PassManagerINS_6ModuleENS_15AnalysisManagerIS4_IEEEIEEENS_8ArrayRefINS_11PassBuilder15PipelineElementEEEEELb0EE4growEy]+0x17b): undefined reference to `llvm::report_bad_alloc_error(char const*, bool)'
collect2: error: ld returned 1 exit status

Change-Id: I1d27c7e3f441197f3f1da98b6a832502b30208d7